---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{service.namespace}}
  annotations:
    getambassador.io/config: |
{% if build.profile.name == "stable" %}
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ghas-{{ build.profile.name }}
      prefix: /
      host: ghas.k736.net
      service:  ghas-{{ build.profile.name }}.dashboard
{% else %}
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ghas-{{ build.profile.name }}
      prefix: /
      host: {{ build.profile.name }}.kubernaut.io
      service:  ghas-{{ build.profile.name }}.{{service.namespace}}
{% endif %}
spec:
  selector:
    app: {{ build.name }}
  ports:
    - name: http-api
      port: 80
      targetPort: http-api
  type: ClusterIP

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ build.name }}
  namespace: {{service.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ build.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: {{ build.name }}
      name: {{ build.name }}
    spec:
      containers:
        - name: {{ build.name }}
          image: {{ build.images["Dockerfile"] }}
          imagePullPolicy: IfNotPresent
          env:
            - name: GITHUB_USER
              value: d6e-automaton

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ghas
                  key: GITHUB_TOKEN
          ports:
            - name: http-api
              containerPort: 5000
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
